spring:
  profiles:
    active: dev
  datasource:
    url: "jdbc:postgresql://localhost:5432/bookdb"
    username: "user"
    password: "p@ssw0rd"
    driver-class-name: "org.postgresql.Driver"

    # HikariCP settings
    hikari:
      maximum-pool-size: 10
      minimum-idle: 0
      idle-timeout: 100000
      max-lifetime: 3000000
      read-only: false
      connection-init-sql: "SELECT 1"
      auto-commit: false